#!/bin/bash
set -x

CURRENT_DIR="`pwd`";cd "`dirname \"$0\"`";SCRIPT_DIR="`pwd`";cd "$CURRENT_DIR"

source "$SCRIPT_DIR"/base
source "$SCRIPT_DIR"/config

DOCKER_BUILD_TAG_BASE="$DOCKER_ID/$DOCKER_REPOSITORY"
DOCKER_BUILD_TAG_CURRENT="$DOCKER_BUILD_TAG_BASE:${STORBACKUP_VERSION}_${DOCKER_IMAGE_VERSION}_$DOCKER_IMAGE_REVERSION"
DOCKER_BUILD_TAG_LATEST="$DOCKER_BUILD_TAG_BASE:latest"
BUILD_DATE="`date --utc`"

sed -e "s/<IMAGE_BUILD_DATE>/$BUILD_DATE/" \
    -e "s/<IMAGE_VERSION>/$DOCKER_IMAGE_VERSION/" \
    -e "s/<IMAGE_REVERSION>/$DOCKER_IMAGE_REVERSION/" \
    <"$DOCKERFILE_TEMPLATE" \
    >"$DOCKERFILE"

docker image rm "$DOCKER_BUILD_TAG_CURRENT" "$DOCKER_BUILD_TAG_LATEST"
docker image build --tag "$DOCKER_BUILD_TAG_CURRENT" --tag "$DOCKER_BUILD_TAG_LATEST" "$DOCKERBUILD_DIR"
