#!/bin/bash

CURRENT_DIR="`pwd`";cd "`dirname \"$0\"`";SCRIPT_DIR="`pwd`";cd "$CURRENT_DIR"

source "$SCRIPT_DIR"/base
source "$SCRIPT_DIR"/config

DOCKER_BUILD_TAG_BASE="$DOCKER_ID/$DOCKER_REPOSITORY"
DOCKER_BUILD_TAG_CURRENT="$DOCKER_BUILD_TAG_BASE:${STORBACKUP_VERSION}_${DOCKER_IMAGE_VERSION}_$DOCKER_IMAGE_REVERSION"
DOCKER_BUILD_TAG_LATEST="$DOCKER_BUILD_TAG_BASE:latest"

docker image push "$DOCKER_BUILD_TAG_CURRENT"
docker image push "$DOCKER_BUILD_TAG_LATEST"
