#!/bin/bash

CURRENT_DIR="`pwd`";cd "`dirname \"$0\"`";SCRIPT_DIR="`pwd`";cd "$CURRENT_DIR"

source "$SCRIPT_DIR"/base
source "$SCRIPT_DIR"/config

DOCKER_BUILD_TAG_BASE="$DOCKER_ID/$DOCKER_REPOSITORY"
DOCKER_BUILD_TAG_CURRENT="$DOCKER_BUILD_TAG_BASE:${STORBACKUP_VERSION}_${DOCKER_IMAGE_VERSION}_$DOCKER_IMAGE_REVERSION"

TAR_FILE_BASENAME="`echo \"$DOCKER_BUILD_TAG_CURRENT\"|sed s'|/|-|'`.tar"
TAR_FILE="$TARFILE_DIR"/"$TAR_FILE_BASENAME"

docker image save --output "$TAR_FILE" "$DOCKER_BUILD_TAG_CURRENT"
